project:
  type: website
  output-dir: docs
website:
  #title: "Feed"
  image: "SAP_website-image_TRANSPARENT.png"
  favicon: "favicon_logo.png"
  navbar: 
    logo: "SAP_website-image_TRANSPARENT.png"
    logo-alt: "SAP"
    collapse-below: lg
    right:
      #   text: ""
      # - href: index.qmd
      - text: Our approach
        href: about.qmd
      # - text: "Study species"
      #   menu: 
      #     - salmonids.qmd
      #     - crustaceans.qmd
      - text: Our team
        href: people.qmd
      - text: Our research 
        href: publications.qmd
      # - text: Contact us
      #   file: contactpage.qmd
      - text: News
        href: news.qmd
      - icon: github
        href: https://github.com/Sustainable-Aquafeeds-Project
      
format:
  html:
    theme: 
      light: lux
    css: styles.css
    toc: true

editor: visual

