project:
  type: website
  output-dir: docs
website:
  #title: "Feed"
  image: "SAP_website-image_TRANSPARENT.png"
  favicon: "favicon_logo.png"
  navbar: 
    logo: "SAP_website-image_TRANSPARENT.png"
    logo-alt: "SAP"
    collapse-below: lg
    pinned: true
    right:
      - text: "Home"
        href: index.qmd #change padding b/w navbar and image
      - text: Our approach
        href: about.qmd
      # - text: "Study species"
      #   menu: 
      #     - salmonids.qmd
      #     - crustaceans.qmd
      - text: Our team
        href: people.qmd
     # - text: Our research 
      #  href: publications.qmd
      # - text: Contact us
      #   file: contactpage.qmd
      - text: Our research 
        href: research.qmd
      - text: News
        href: news.qmd
      - icon: github
        href: https://github.com/Sustainable-Aquafeeds-Project
      - icon: envelope
        href: mailto:julia.blanchard@utas.edu.au
  page-footer:
      background: "#094867"
      left:  Copyright &copy; 2023 [Sustainable Aquafeeds Project](https://sustainable-aquafeeds-project.github.io/)
      center: |
        This project is supported by ![](/photos/logos/ARC_Research_Council.png){width=200px}
      right: "Built using [Quarto](https://quarto.org/)"

  #  right: |
   #   [Terms & Conditions](/ts-and-cs.qmd)    
format:
  html:
    theme: [lux,custom.scss]
   # css: style.css
    

editor: visual

