project:
  type: website
  output-dir: docs
website:
  #title: "Feed"
  image: "SAP_website-image_TRANSPARENT.png"
  favicon: "favicon_logo.png"
  sidebar: false
  navbar: 
    logo: "SAP_website-image_TRANSPARENT.png"
    logo-alt: "SAP"
    collapse-below: lg
    pinned: true
    right:
      - text: "Home"
        href: index.qmd #change padding b/w navbar and image
      - text: Our approach
        href: about.qmd
      # - text: "Study species"
      #   menu: 
      #     - salmonids.qmd
      #     - crustaceans.qmd
      - text: Our team
        href: people.qmd
      - text: Our research 
        href: publications.qmd
      # - text: Contact us
      #   file: contactpage.qmd
      - text: News
        href: news.qmd
      - icon: github
        href: https://github.com/Sustainable-Aquafeeds-Project
        
  page-footer:
      background: "#094867"
      center:
      - text: Contact us
        href: mailto:sowdamini.sp@gmail.com

  #  right: |
   #   [Terms & Conditions](/ts-and-cs.qmd)    
format:
  html:
    theme: [lux,custom.scss]
    #css: styles.css
    

editor: visual

