project:
  type: website
  output-dir: docs
website:
  title: "Feed"
  image: "SAP_website-image.jpg"
  favicon: "favicon_logo.png"
  navbar: 
    logo: "SAP_website-image.jpg"
    logo-alt: "SAP"
    collapse-below: lg
    right:
      #   text: ""
      # - href: index.qmd
      - text: About
        href: about.qmd
      # - text: "Study species"
      #   menu: 
      #     - salmonids.qmd
      #     - crustaceans.qmd
      - text: People
        href: people.qmd
      - text: Outputs 
        href: publications.qmd
      # - text: Contact us
      #   file: contactpage.qmd
      - text: News
        href: news.qmd
      - icon: github
        href: https://sustainable-aquafeeds-project.github.io/
      
format:
  html:
    theme: 
      light: lux
    css: styles.css
    toc: true

editor: visual

